version: '3.3'

services:

  navigator-configuration-api:
    container_name: 'navigator-configuration-api'
    image: "stuartshay/navigator-configuration-api:3.1.1.27"
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - EndPointConfiguration__NavigatorMapsApi=http://maps-api
     - EndPointConfiguration__NavigatorAttractionsApi=http://attractions-api
     - EndPointConfiguration__NavigatorReportsApi=http://reports-apl
    ports:
     - "7300:7300"
    networks:
      - navigator-network

networks:
  navigator-network:

