version: '3.3'

services:

  navigator-configuration-api:
    container_name: 'navigator-configuration-api'
    image: "stuartshay/navigator-configuration-api:3.1.1.24"
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - EndPointConfiguration__NavigatorMapsApi=http://mapsapi
    ports:
     - "80:80"
    networks:
      - navigator-network

networks:
  navigator-network:

